### ISSUE TITLE
lib/blas.h:25:50: error: field initializer is not constant

### ISSUE THREAD

**Issue by huangmeng123** [lmnt-com/haste#20]
Hi,

I was trying to build the haste_pytorch but it failed to build the code at the first step ("make haste_pytorch"). Here is the error message I got:

```
$ make haste_pytorch 
nvcc -ccbin g++ -gencode arch=compute_37,code=compute_37 -gencode arch=compute_60,code=compute_60 -c lib/lstm_forward_gpu.cu.cc -o lib/lstm_forward_gpu.o -std=c++11 -x cu -Xcompiler -fPIC -I/usr/include/eigen3 -I/lib/cuda-9.0/include -Ilib -O3
lib/blas.h:25:50: error: field initializer is not constant
   static constexpr decltype(cublasHgemm)* gemm = cublasHgemm;
                                                  ^
lib/blas.h:30:53: error: field initializer is not constant
   static constexpr decltype(cublasSgemm)* gemm = cublasSgemm;
                                                     ^
lib/blas.h:35:53: error: field initializer is not constant
   static constexpr decltype(cublasDgemm)* gemm = cublasDgemm;
                                                     ^
make: *** [Makefile:30: haste] Error 1

```

**Comment by huangmeng123** [comment]
It passed the previous error, but now I got the following one:

```
pytorch/layer_norm_lstm.cc:16:35: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
                                   ^
compilation terminated.
error: command 'gcc' failed with exit status 1
make: *** [Makefile:71: haste_pytorch] Error 1

```
and a warning like this:
```
                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!
```

I guess I can switch to a higher version of gcc to fix the warning (and the original error as well), but not sure what causes the missing file one.

**Comment by sharvil** [comment]
Which version of PyTorch are you using?

**Comment by huangmeng123** [comment]
0.4.1

**Comment by sharvil** [comment]
Yeah, that's quite an old version of PyTorch without a stable API. You'll need a newer version to use Haste. I've confirmed that Haste builds and runs successfully with PyTorch 1.4 and 1.5, but there's a good chance it'll work with 1.2 and 1.3 as well.

**Comment by huangmeng123** [comment]
Oh, yea, PyTorch was required to be v1.2+ for this project. Good to know. Thanks!
